### ISSUE TITLE
Package suggestion: regress

### ISSUE THREAD

**Issue by ggrothendieck** [cran-task-views/MixedModels#30]
regress: Gaussian Linear Models with Linear Covariance Structure

Functions to fit Gaussian linear model by maximising the residual log likelihood where the covariance structure can be written as a linear combination of known matrices. Can be used for multivariate models and random effects models. Easy straight forward manner to specify random effects models, including random interactions. Code now optimised to use Sherman Morrison Woodbury identities for matrix inversion in random effects models. We've added the ability to fit models using any kernel as well as a function to return the mean and covariance of random effects conditional on the data (best linear unbiased predictors, BLUPs). Clifford and McCullagh (2006) <https://www.r-project.org/doc/Rnews/Rnews_2006-2.pdf>.

**Comment by bbolker** [comment]
Hmm.  This certainly fits within the scope (I think it would go in the "frequentist mixed models" section, but to be honest I'm wondering/curious where its advantages lie over other packages - is there some particular use case this is good for that we can highlight in the task view?

**Comment by kbroman** [comment]
I think what’s special is the “…where the covariance structure can be written as a linear combination of known matrices.” Rather than specify random effects with an implied variance structure, you give the variance structure more directly. There are some applications in spatial data and also in genetics where this is more natural.

**Comment by bbolker** [comment]
bac839bd47d345b108
